name: d7tod8migrate
recipe: drupal8
env_file:
  - config/config.env
config:
  webroot: drupal8/web
  config:
    php: config/php.ini
    database: config/my.cnf
services:
  appserver:
    webroot: drupal8/web
    xdebug: true
  drupal7db:
    type: mysql
    portforward: true
    creds:
      user: drupal7
      password: drupal7
      database: drupal7
tooling:
  mi-init:
    description: Initialise some default migration setup.
    service: appserver
    cmd: scripts/mi-init.sh
    user: root
  mist:
    description: View migration status
    cmd:
      - appserver: drush -r /app/drupal8/web migrate-status
  miup:
    description: Dump D8 database and run migrate-upgrade
    service: appserver
    cmd:
      - mkdir -p /app/exports/data
      - drupal --root=/app/drupal8/web dbdu --gz && mv /app/drupal8/web/drupal8**.sql.gz /app/exports/data
      - drush -r /app/drupal8/web migrate-upgrade --configure-only --legacy-db-key=drupal7db --legacy-root=/app/imports/files/
  miip:
    description: Perform a migrate-import
    cmd:
      - appserver: drush -r /app/drupal8/web migrate-import --all
  mirs:
    description: Perform a migrate-reset-status
    cmd:
      - appserver: drush -r /app/drupal8/web migrate-reset-status
