name: d7tod8migrate
recipe: drupal8
config:
  webroot: drupal8/web
  config:
    php: config/php.ini
    database: config/my.cnf
services:
  appserver:
    xdebug: true
    build_as_root:
      - /app/scripts/appserver_build.sh
  drupal7db:
    type: mysql
    portforward: true
    creds:
      user: drupal7
      password: drupal7
      database: drupal7
tooling:
  phpunit:
    description: "Run PHP Unit tests: lando phpunit"
    service: appserver
    # cmd: /app/drupal8/vendor/bin/phpunit -c /app/drupal8/phpunit.xml /app/drupal8/web/modules/migrate
    cmd: "/app/drupal8/vendor/bin/phpunit --debug -c /app/drupal8/phpunit.xml --printer=\\Drupal\\Tests\\Listeners\\HtmlOutputPrinter /app/drupal8/web/modules/migrate"
  phpcs:
    description: Run PHPCS checks against all custom Drupal 8 code (modules, migrations, themes) e.g. 'lando phpcs'
    service: appserver
    cmd: /app/drupal8/phpcs.sh "/app/drupal8" "/app/drupal8/web/modules/custom /app/drupal8/web/modules/migrate /app/drupal8/web/themes/custom/nidirect"
  drck:
    description: Run drupal-check for Drupal 9 compatibility e.g. 'lando drck ./'
    service: appserver
    cmd: /app/drupal8/vendor/bin/drupal-check
  drush:
    server: appserver
    cmd: drush -r /app/drupal8/web
  mi-init:
    description: Initialise some default migration setup.
    service: appserver
    cmd: /app/scripts/mi-init.sh
    user: root
  mist:
    description: View migration status
    cmd:
      - appserver: drush -r /app/drupal8/web migrate-status
  miup:
    description: Dump D8 database and run migrate-upgrade
    service: appserver
    cmd:
      - drupal dbdu --gz && mv drupal8**.sql.gz /app/exports/data
      - drush -r /app/drupal8/web migrate-upgrade --configure-only --legacy-db-key=drupal7db --legacy-root=/app/imports/files/
  miip:
    description: Perform a migrate-import
    cmd:
      - appserver: drush -r /app/drupal8/web migrate-import
  mirs:
    description: Perform a migrate-reset-status
    cmd:
      - appserver: drush -r /app/drupal8/web migrate-reset-status
