recipe: drupal8
config:
  webroot: drupal8/web
  database: mariadb
  php: '7.4'
  config:
    php: config/php.ini
    database: config/my.cnf
compose:
  - docker-compose.yml
env_file:
  - config/.env
services:
  appserver:
    # See https://xdebug.org/docs/all_settings#mode for XDebug modes.
    # Use comma's to enable multiple modes e.g. develop,debug.
    xdebug: debug
    build_as_root:
      - /app/scripts/appserver_build.sh
  redis:
    type: redis:5.0
    persist: true
    config:
        server: config/redis.conf
  solr:
    type: solr:7
    portforward: true
    core: default
    config:
      dir: config/solr/7.x/default
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
  yarn:
    service: appserver
    cmd: yarn
  nightwatch:
    service: appserver
    description: "Run Nightwatch.js functional tests.\n\n
                  Usage:\n
                  > Run a specific test with tag\n
                  lando nightwatch --tag your-tag\n
                  > Run a single test suite file, relative to Drupal core location\n
                  lando nightwatch ../modules/custom/modulename/tests/src/Nightwatch/Tests/yourTestSuite.js\n
                  > Run all tests except Core\n
                  lando nightwatch --skiptags core\n"
    cmd: "yarn --cwd=/app/drupal8/web/core test:nightwatch"
  phpunit:
    description: "Run PHPUnit tests. You can pass options, e.g. --group=nidirect, as you require"
    service: appserver
    cmd: cd /app/drupal8/web/core && /app/drupal8/vendor/bin/phpunit -c /app/drupal8/web/core/phpunit.xml
  phpcs:
    description: Run PHPCS checks against all custom Drupal 8 code (modules, migrations, themes) e.g. 'lando phpcs'
    service: appserver
    cmd: /app/drupal8/phpcs.sh "/app/drupal8" "/app/drupal8/web/modules/origins /app/drupal8/web/modules/custom /app/drupal8/web/modules/migrate /app/drupal8/web/themes/custom /app/drupal8/web/profiles/custom"
  drck:
    description: Run drupal-check for Drupal 9 compatibility e.g. 'lando drck ./'
    service: appserver
    cmd: /app/drupal8/vendor/bin/drupal-check
  drush:
    server: appserver
    cmd: drush -r /app/drupal8/web
  mist:
    description: View migration status
    cmd:
      - appserver: drush -r /app/drupal8/web migrate-status --tag="NIDirect"
  miup:
    description: Dump D8 database and run migrate-upgrade
    service: appserver
    cmd:
      - drupal dbdu --gz && mv drupal8**.sql.gz /app/exports/data
  miip:
    description: Perform a migrate-import
    cmd:
      - appserver: drush -r /app/drupal8/web migrate-import --feedback=100
  mirb:
    description: Perform a migrate-rollback
    cmd:
      - appserver: drush -r /app/drupal8/web migrate:rollback
  mirs:
    description: Perform a migrate-reset-status
    cmd:
      - appserver: drush -r /app/drupal8/web migrate-reset-status
  imp:
    description: Import Configuration and Structure
    cmd:
      - appserver: drush -r /app/drupal8/web cr -y && drush -r /app/drupal8/web cim -y && drush -r /app/drupal8/web ia --choice=safe
  devmode:
    service: appserver
    description: Clone all DOF development repositories
    cmd: "sh /app/scripts/setup-for-dev.sh"
    user: root
  basic-auth:
    service: appserver
    description: Enable basic authentication
    cmd: "sh /app/scripts/basic-auth.sh"
    user: root
