recipe: drupal8
config:
  webroot: drupal8/web
  config:
    php: config/php.ini
    database: config/my.cnf
compose:
  - docker-compose.yml
services:
  appserver:
    xdebug: true
    build_as_root:
      - /app/scripts/appserver_build.sh
  memcached:
    type: memcached
    portforward: true
  drupal7db:
    type: mysql
    portforward: true
    creds:
      user: drupal7
      password: drupal7
      database: drupal7
tooling:
  yarn:
    service: appserver
    cmd: yarn
  nightwatch:
    service: appserver
    description: "Run Nightwatch.js functional tests"
    cmd: "cd /app/drupal8/web/core && yarn test:nightwatch"
  phpunit:
    description: "Run PHPUnit tests. You can specify also options, e.g. --testsuite=unit, or path to module(s) to test."
    service: appserver
    cmd: cd /app/drupal8/web/core && /app/drupal8/vendor/bin/phpunit -c phpunit.xml
  phpcs:
    description: Run PHPCS checks against all custom Drupal 8 code (modules, migrations, themes) e.g. 'lando phpcs'
    service: appserver
    cmd: /app/drupal8/phpcs.sh "/app/drupal8" "/app/drupal8/web/modules/custom /app/drupal8/web/modules/migrate /app/drupal8/web/themes/custom/nidirect"
  drck:
    description: Run drupal-check for Drupal 9 compatibility e.g. 'lando drck ./'
    service: appserver
    cmd: drupal-check
  drush:
    server: appserver
    cmd: drush -r /app/drupal8/web
  mist:
    description: View migration status
    cmd:
      - appserver: drush -r /app/drupal8/web migrate-status
  miup:
    description: Dump D8 database and run migrate-upgrade
    service: appserver
    cmd:
      - drupal dbdu --gz && mv drupal8**.sql.gz /app/exports/data
      - drush -r /app/drupal8/web migrate-upgrade --configure-only --legacy-db-key=drupal7db --legacy-root=/app/imports/files/
  miip:
    description: Perform a migrate-import
    cmd:
      - appserver: drush -r /app/drupal8/web migrate-import
  mirb:
    description: Perform a migrate-rollback
    cmd:
      - appserver: drupal -r /app/drupal8/web migrate-rollback --source-base_path=/app/drupal8/web
  mirs:
    description: Perform a migrate-reset-status
    cmd:
      - appserver: drush -r /app/drupal8/web migrate-reset-status
