# Copy this file to .lando.local.yml and edit the name value below.
name: my-hugo-duncan-fansite
# >>>=== XDEBUG ===>>>
# Uncomment the config setting below and set the bool for enabling/disabling xdebug.
# Setting xdebug to false should improve the performance of your site at the cost of
# preventing the use of the xdebug debugger. Once your site is running you can also use
# 'lando xdebug-on/xdebug-off' to enable/disable the xdebug module.
# config:
#   xdebug: true
# >>>=== TURBO-MODE ===>>>
# DO NOT enable turbomode during a clean install as the Drupal build process will fail.
# Uncomment the yaml section below to enable the MACOS filesystem speedhack
# which will improve the performance of your lando instance.
# If you enable this, your Drupal vendor directory will be synced to the container
# on build and excluded from the volume. This means changes on the host will NOT
# carry over to the container. If you run composer commands on the host YOU MUST
# run the same command using 'lando composer' to apply those to the container.
# You may need to do a lando rebuild and/or restart docker for this kick in.
#
# excludes:
#  - drupal8/vendor
